config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  resources :notes, only: [:create, :new, :edit, :update]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :title, :recording, presence: true

  has_many :tracks
  belongs_to :band
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, presence: true

  belongs_to :user
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :album_id, :song, presence: true

  belongs_to :album
  has_many :notes
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :notes

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil unless @user
    @user.is_password?(password) ? @user : nil
  end

  attr_reader :password
  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def is_password?(password)
    bc_obj = BCrypt::Password.new(self.password_digest)
    bc_obj.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user

  def new
  end

  def show
    @album = Album.find_by_id(params[:id])
    render :show
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(album_params[:band_id])
    end
  end

  def edit
  end

  def update
    @album = Album.find_by_id(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url
    end
  end

  def destroy
    @album = Album.find_by_id(params[:id])
    @album.delete if @album
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:title, :band_id, :recording)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user

  def index
    @bands = Band.all
    render :index
  end

  def new
  end

  def show
    @band = Band.find_by_id(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find_by_id(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by_id(params[:id])
    @band.delete if @band
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(session_params[:email],session_params[:password])
    login(user)
    redirect_to user_url(user)
  end

  def destroy
    logout(current_user)
    redirect_to new_session_url
  end

  private
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user

  def new
  end

  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_track_url
    end
  end

  def edit
    @track = Track.find_by_id(params[:id])
    render :edit
  end

  def update
    @track = Track.find_by_id(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to edit_track_url
    end
  end

  def destroy
    @track = Track.find_by_id(params[:id])
    @track.delete if @track
    redirect_to bands_url
  end

  private
  def track_params
    params.require(:track).permit(:song, :album_id, :track_type, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/_footer.html.erb
<nav>
  <%= button_to "Add Track", new_album_track_url(@album), method: :get %>
  <%= button_to "Back to Band", band_url(@album.band_id), method: :get %>
  <%= button_to "Edit Album", edit_album_url, method: :get %>
  <%= button_to "Delete Album", album_url(@album), method: :delete %>
</nav>

app/views/albums/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value= "<%= method %>">
  <%= auth_token %>
  <label>
    Band
    <select name="album[band_id]">
      <% Band.all.each do |band| %>
        <option <%= "selected" if band.id == band_id %> value="<%= band.id %>">
          <%= band.name %></option>
      <% end %>
    </select>
  </label>
  <br>
  <label>
    Title
    <input type="text" name="album[title]" value="<%= album ? album.title : nil %>">
  </label>
  <br>
  <section>
    <input type="radio" name="album[recording]" id="album_recording"
      value="Live Recording"
      <%= "checked" if album && album.recording == "Live Recording" %>>
    <label for="album_recording">Live Recording</label>
    <input type="radio" name="album[recording]" id="album_recording"
      value="Studio Album"
      <%= "checked" if album && album.recording == "Studio Album" %>>
    <label for="album_recording">Studio Album</label>
  </section>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/albums/edit.html.erb
<h2>Edit an Album</h2>

<%= render "form", action:album_url(params[:id]), method: :patch,
  album: Album.find_by_id(params[:id]),
  band_id:Album.find_by_id(params[:id]).band_id %>

app/views/albums/new.html.erb
<h2>Add an Album</h2>

<%= render "form", action:albums_url, method: :post,
  album: nil, band_id: params[:band_id].to_i %>

app/views/albums/show.html.erb
<h2><%= @album.title %></h2>
<p><%= @album.recording %></p>
<br>
<ul>
  <% Track.where(album_id: @album.id).each do |track|%>
    <li>
      <%= link_to track.song, track_url(track) %>
    </li>
  <% end %>
</ul>

<%= render "footer" %>

app/views/bands/_footer.html.erb
<nav>
  <%= button_to "Add Album", new_band_album_url(@band), method: :get %>
  <%= button_to "Bands Index", bands_url, method: :get %>
  <%= button_to "Edit Band", edit_band_url, method: :get %>
  <%= button_to "Delete Band", band_url(@band), method: :delete %>
</nav>

app/views/bands/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value= "<%= method %>">
  <%= auth_token %>
  <label>
    Name
    <input type="text" name="band[name]" value="<%= band ? band.name : nil %>">
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/bands/edit.html.erb
<h2>Edit Band</h2>

<%= render "form", action: band_url(@band), method: :patch, band: @band%>

app/views/bands/index.html.erb
<h2>Bands</h2>

<ul>
  <% Band.all.each do |band| %>
    <li>
      <%= link_to band.name, band_url(band) %>
    </li>
  <% end %>
</ul>

<%= button_to "Add Band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h2>Add a Band</h2>

<%= render "form", action: bands_url, method: :post, band: @band%>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

<ul>
  <% Album.where(band_id: @band.id).each do |album| %>
    <li>
      <%= link_to album.title, album_url(album) %>
    </li>
  <% end %>
</ul>

<%= render "footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<header>
  <h1>MusicApp</h1>
  <br>
  <%= link_to "Sign Up", new_user_url%>
  <% if current_user %>
    <%= button_to "Logout", session_url, method: :delete %>
  <% else %>
    <%= button_to "Login", new_session_url, method: :get %>
  <% end %>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <p>Enter a note as <%= current_user.email %>:</p>
  <textarea ></textarea>
</form>

app/views/notes/_notes.html.erb
<p><%= User.find_by_id(note.user_id).email %> posted:</p><br>
<p><%= note.body %></p>
<br><br>

app/views/tracks/_footer.html.erb
<nav>
  <%= button_to "Edit Track", edit_track_url(@track), method: :get %>
  <%= button_to "Delete Track", track_url, method: :delete %>
  <%= button_to "Back to Album", album_url(@track.album_id), method: :get %>
</nav>

app/views/tracks/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value= "<%= method %>">
  <%= auth_token %>
  <label for="track_album_id">Album</label>
  <select id="track_album_id" name="track[album_id]" >
    <% Album.all.each do |album| %>
    <option value="<%= album.id %>" <%= "selected" if album.id == album_id%>>
      <%= album.title %>
    </option>
    <% end %>
  </select>
  <br>
  <label>
    Song name
    <input type="text" name="track[song]" value="<%= @track ? @track.song : nil %>">
  </label>
  <br>
  <label for="track_type">Regular</label>
  <input type="radio" name="track[track_type]" id="track_type" value="Regular"
    <%= "checked" if track && track.track_type == "Regular"%>>
  <label for="track_type">Bonus</label>
  <input type="radio" name="track[track_type]" id="track_type" value="Bonus"
    <%= "checked" if track && track.track_type == "Bonus"%>>
  <br>
  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= @track ? @track.lyrics : nil %></textarea>
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/tracks/edit.html.erb
<h2>Edit a Track</h2>
<p><%= @track.song %></p>

<%= render "form", action: track_url(@track), method: :patch, track: @track,
  album_id: Track.find_by_id(params[:id]).album_id %>

app/views/tracks/new.html.erb
<h2>Add a Track</h2>

<%= render "form", action: tracks_url, method: "POST", track: nil,
  album_id: params[:album_id].to_i%>

app/views/tracks/show.html.erb
<h2><%= @track.song %></h2>

<body>
  <p><%= @track.track_type %> Track</p>
  <br>
  <p><%= @track.lyrics %></p>
  <br>
  <%= render "notes/form" %>
  <ul>
    <% @track.notes.each do |note|%>
    <li>
      <% render "notes/note", note: note %>
    </li>
    <% end %>
  </ul>
</body>

<%= render 'footer', track: @track %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <label>
    Email
    <input type="text" name="user[email]" id="user_email">
  </label>
  <br>
  <label>
    Password
    <input type="password" name="user[password]" id="user_password">
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<p><%=@user.email%></p>

<%= button_to "Bands", bands_url, method: :get %>